name: punisher
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - bleach=2.0.0
  - entrypoints=0.2.3
  - html5lib=1.0.1
  - icu=58.2
  - ipykernel=4.7.0
  - ipython=6.2.1
  - jedi=0.10.2
  - jinja2=2.10
  - jupyter_client=5.2.1
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.3.3
  - jupyter_highlight_selected_word=0.1.0
  - jupyter_latex_envs=1.4.0
  - jupyter_nbextensions_configurator=0.3.0
  - libiconv=1.15
  - libsodium=1.0.15
  - libxml2=2.9.7
  - libxslt=1.1.32
  - lxml=4.1.1
  - markupsafe=1.0
  - mistune=0.8.3
  - nbconvert=5.3.1
  - notebook=5.2.2
  - pandoc=2.1
  - pandocfilters=1.4.1
  - pexpect=4.3.1
  - pickleshare=0.7.4
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - pyyaml=3.12
  - pyzmq=16.0.2
  - simplegeneric=0.8.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=4.5.3
  - wcwidth=0.1.7
  - webencodings=0.5
  - yaml=0.1.7
  - zeromq=4.2.1
  - asn1crypto=0.24.0
  - ca-certificates=2017.08.26
  - certifi=2017.11.5
  - cffi=1.11.2
  - chardet=3.0.4
  - cryptography=2.1.4
  - cycler=0.10.0
  - decorator=4.1.2
  - freetype=2.8
  - idna=2.6
  - intel-openmp=2018.0.0
  - ipython_genutils=0.2.0
  - jsonschema=2.6.0
  - jupyter_core=4.4.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.32
  - matplotlib=2.1.1
  - mkl=2018.0.1
  - nbformat=4.4.0
  - ncurses=6.0
  - numpy=1.14.0
  - openssl=1.0.2n
  - pandas=0.22.0
  - patsy=0.5.0
  - pip=9.0.1
  - plotly=2.2.2
  - pycparser=2.18
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pysocks=1.6.7
  - python=3.6.4
  - python-dateutil=2.6.1
  - pytz=2017.3
  - readline=7.0
  - requests=2.18.4
  - scipy=1.0.0
  - seaborn=0.8.1
  - setuptools=36.5.0
  - six=1.11.0
  - sqlite=3.20.1
  - statsmodels=0.8.0
  - tk=8.6.7
  - traitlets=4.3.2
  - urllib3=1.22
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - aiodns==1.1.1
    - aiohttp==2.3.7
    - async-timeout==2.0.0
    - cchardet==2.1.1
    - ccxt==1.10.544
    - click==6.7
    - dash==0.19.0
    - dash-core-components==0.15.5
    - dash-html-components==0.8.0
    - dash-renderer==0.11.1
    - dash-table-experiments==0.5.3
    - filelock==2.0.7
    - flask==0.12.2
    - flask-compress==1.4.0
    - itsdangerous==0.24
    - jupyterthemes==0.18.3
    - lesscpy==0.11.2
    - multidict==3.3.2
    - parso==0.1.1
    - ply==3.10
    - poloniex==0.0.12
    - pycares==2.3.0
    - pymongo==3.6.0
    - python-dotenv==0.7.1
    - werkzeug==0.14.1
    - yarl==0.18.0
